Corrected Caput 1, resubmitting
scta-texts/lca8s8 pull request #3
Opened 2024-07-26 13:46 UTC by a1wilson

Thanks for the suggested corrections
- I removed all of the n="P"

2024-07-29 22:01 UTC, jeffreycwitt requested changes

2024-07-29 22:01 UTC, jeffreycwitt commented on lca8s8-d1e52/cod-dlc9qq_lca8s8-d1e52.xml
> +		<head id="P">Caput 1 [Bnf 12926 Transcription]</head>
```suggestion
		<head>Caput 1 [Bnf 12926 Transcription]</head>
```

2024-07-29 22:01 UTC, jeffreycwitt commented on lca8s8-d1e52/cod-dlc9qq_lca8s8-d1e52.xml
> +		<head id="P">Caput 1 [Bnf 12926 Transcription]</head>
small schema error that needs to be fixed.

2024-07-30 11:33 UTC, a1wilson commented on lca8s8-d1e52/cod-dlc9qq_lca8s8-d1e52.xml
> +		<head id="P">Caput 1 [Bnf 12926 Transcription]</head>
Got it. I changed this in my template for future chapters.

2024-07-31 01:50 UTC, jeffreycwitt approved these changes
Looks great! I'm merging now.

2024-07-31 01:50 UTC, merged